# generated by datamodel-codegen:
#   filename:  models.json
#   timestamp: 2025-03-18T07:03:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel


class NotificationTelegramSendRequest(BaseModel):
    title: str
    message: str


class Versions(Enum):
    v1 = 'v1'
